database:
  user: "meuse"
  password: !secret "meuse"
  host: "127.0.0.1"
  port: 5432
  name: "meuse"
http:
  address: 0.0.0.0
  port: 8855
logging:
  level: debug
  console:
    encoder: json
  overrides:
    org.eclipse.jetty: info
    com.zaxxer.hikari.pool.HikariPool: info
    org.apache.http: error
    io.netty.buffer.PoolThreadCache: error
    org.eclipse.jgit.internal.storage.file.FileSnapshot: info
    com.amazonaws.auth.AWS4Signer: warn
    com.amazonaws.retry.ClockSkewAdjuster: warn
    com.amazonaws.request: warn
    com.amazonaws.requestId: warn
metadata:
  type: "shell"
  path: "registry"
  target: "origin/master"
  url: "https://github.com/mcorbin/testregistry"
crate:
  store: "filesystem"
  path: "crates"
frontend:
  enabled: true
  secret: !envsecret "FRONTEND_SECRET"
  public: false
  repository: "https://github.com/mcorbin/meuse"
  documentation: "https://meuse.mcorbin.fr/"
  title: "Meuse"
